<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23499" started-at="2024-10-31T11:26:49Z" finished-at="2024-10-31T11:27:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23499" started-at="2024-10-31T11:26:49Z" finished-at="2024-10-31T11:27:12Z">
      <class name="com.project.utilities.ExtentReportwithFailedScreenShot">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.project.utilities.ExtentReportwithFailedScreenShot@6385cb26]" name="setUp" is-config="true" duration-ms="11368" started-at="2024-10-31T16:56:49Z" finished-at="2024-10-31T16:57:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest001()[pri:0, instance:com.project.utilities.ExtentReportwithFailedScreenShot@6385cb26]" name="loginTest001" duration-ms="11182" started-at="2024-10-31T16:57:00Z" finished-at="2024-10-31T16:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest001 -->
        <test-method status="FAIL" signature="testcases002()[pri:1, instance:com.project.utilities.ExtentReportwithFailedScreenShot@6385cb26]" name="testcases002" duration-ms="13" started-at="2024-10-31T16:57:11Z" finished-at="2024-10-31T16:57:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Pradeep] but found [Swag Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Pradeep] but found [Swag Labs]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.project.utilities.ExtentReportwithFailedScreenShot.testcases002(ExtentReportwithFailedScreenShot.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcases002 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.project.utilities.ExtentReportwithFailedScreenShot@6385cb26]" name="tearDown" is-config="true" duration-ms="901" started-at="2024-10-31T16:57:11Z" finished-at="2024-10-31T16:57:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.project.utilities.ExtentReportwithFailedScreenShot -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
